name: currency_exchange_app
description: An application that displays currency exchange rates.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5  # Untuk melakukan HTTP requests
  intl: ^0.18.0  # Untuk format angka dan tanggal
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true